// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ms_account_and_credit_card.DB;

namespace msvoomaaccountandcredit.Migrations
{
    [DbContext(typeof(DBCtx))]
    partial class DBCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ms_account_and_credit_card.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BankCode");

                    b.Property<int>("CustomerId");

                    b.Property<int>("Iban");

                    b.Property<string>("Status");

                    b.HasKey("AccountId");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("ms_account_and_credit_card.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<string>("CardAlias");

                    b.Property<string>("CardType");

                    b.HasKey("CardId");

                    b.HasIndex("AccountId");

                    b.ToTable("cards");
                });

            modelBuilder.Entity("ms_account_and_credit_card.Models.Card", b =>
                {
                    b.HasOne("ms_account_and_credit_card.Models.Account")
                        .WithMany("MyCards")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
